### ISSUE TITLE
smugsync

### ISSUE THREAD

**Issue by gingerlime** [chrishoffman/smugpy#10]
Hey @chrishoffman. Just a quick note to say thanks for smugpy. I'm using it for a small command-line tool I created called [smugline](https://github.com/gingerlime/smugline). It currently only supports uploading files from a local folder, but I hope to extend it to do more in future.

Having smugpy made it very easy for me, so thanks for your great work.

[EDIT: renamed to smugline]

**Comment by gingerlime** [comment]
Of course I would love to get some feedback and collaborate on this in future.

**Comment by chrishoffman** [comment]
Cool project!  I would love to see the Oauth workflow implemented since you don't have to script usernames and passwords.  You could always store the auth token locally and secure it with file permissions.  Nice work on this.

**Comment by gingerlime** [comment]
Thanks. Yes. It's certainly one of the many things I have planned. Ideally I'd like to keep smugline platform-agnostic, so working out the file-permission issues across Windows/Mac/Linux might be a small challenge, but shouldn't stop from implementing something like this.

Unfortunately my SmugMug trial expired and I didn't get the Pro account that they [promise](https://smugmug.atlassian.net/wiki/display/API/Home) for app developers. I'll have to remind / ask them again I guess.
